name: Ubuntu Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache submodules
      id: cache-submodules
      uses: actions/cache@v2
      env:
        cache-name: cache-submodules
      with:
        path: |
          .git/modules/sdk
          ./sdk
        key: ${{ runner.os }}-${{ env.cache-name }}-v1-${{ hashFiles('.gitmodules') }}

    - name: Checkout submodules
      if: steps.cache-submodules.outputs.cache-hit != 'true'
      run: git submodule update --init --recursive

    - name: Setup GCC multilib
      run: |
        sudo apt-get install gcc-multilib g++-multilib

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Build
      run: python build_analyzer.py
